### ISSUE TITLE
Tela muito escura ao ligar

### ISSUE THREAD

**Issue by marcsvg** [rafaelwms/Dell-Latitude-5400#1]
Olá, tenho tido um problema ao ligar meu notebook após a instalação, a tela fica bem escura por um tempo, mas depois de 10/20 minutos volta ao normal, queria saber se teve o mesmo problema e se poderia me ajudar a como resolver essa situação, desde já agradeço

**Comment by rafaelwms** [comment]
Olá!! Não tive esse tipo de experiência não.
Fiz a instalação 3 vezes... usei por pouco tempo que fiquei com a máquina, mas tudo pareceu bem.
