### ISSUE TITLE
Backlight not working on Ventura 13.4

### ISSUE THREAD

**Issue by cvega48** [rafaelwms/Dell-Latitude-5400#2]
I used your EFI but when I updated to 13.4, the backlight is not working anymore. It works up until half of the the boot process. The Apple logo shows well, but then everything turns black as the backlight from the LCD Panel turns off.

As mentioned it worked correctly on previous version of Ventura.

**Comment by rafaelwms** [comment]
Hi There!
Well... I don't have access to a Dell Latitude 5400 machine any more.
I think you can try to update the kexts, or maybe, update the entire EFI to the next Opencore version.
